version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gitsubmodule-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "pip"
    groups:
      uv-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "bun"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase-if-necessary"
    groups:
      bun-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
