name: autofix.ci
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
env:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C
  GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
  UV_FORK_STRATEGY: requires-python
  UV_RESOLUTION: highest
  UV_PRERELEASE: if-necessary-or-explicit
  UV_INDEX_STRATEGY: unsafe-best-match
  UV_NATIVE_TLS: 0
  UV_NO_PROGRESS: 1

jobs:
  autofix:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
      - name: Install the latest version of uv and activate the environment
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          activate-environment: "true"
          github-token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          cache-python: "true"
          resolution-strategy: "highest"
      - run: |
          uv pip install pip
          uv pip install -r requirements.txt
          uv lock -U --fork-strategy requires-python --index-strategy unsafe-best-match --resolution highest
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix-only
      - run: ruff format

      - name: autofix.ci
        uses: autofix-ci/action@v1.3.2
